### ISSUE TITLE
Do a K-fold cross validation for best model.

### ISSUE THREAD

**Issue by imostafizur** [AkshatRastogi-1nC0re/HMS_Titanic_Survivability_Prediction#1]

**Comment by AkshatRastogi-1nC0re** [comment]
Sure, Do you want yo try it out... You can become a contributor

**Comment by imostafizur** [comment]
> Sure, Do you want yo try it out... You can become a contributor

Sure I will

**Comment by AkshatRastogi-1nC0re** [comment]
Creating you a contributor, Make a separate branch and you can start working
